### ISSUE TITLE
Please Add DEMO link

### ISSUE THREAD

**Issue by praveenkumararepalliGit** [just-boris/angular-ymaps#9]
Dear Author,
 Thanks for giving a great contribution.It look awesome if you add Demo Link so that It can be easily testable

**Comment by just-boris** [comment]
Of course, readme has a link to demo. Here it is: http://catatron.com/angular-ymaps/
But unfortunately it is only on Russian, because generally this lib purposed to use here.

Also I can think about english docs, if you really want to have embedded version of https://maps.yandex.com/ on your site

**Comment by praveenkumararepalliGit** [comment]
I am facing a error while loading  <script src = "angular-ymaps.js"> </ script> 

TypeError: Cannot read property '0' of undefined
    at V.e.define.n.panTo (https://api-maps.yandex.ru/2.1.26/release/combine.xml?modules=0a0-0*0b1l1a1…QoQpQrQvQwQxQyQAQBQCQIQLQRQS&jsonp_prefix=ymapsymaps2_1_26_loader:295:3367)
    at Object.fn (http://localhost:8080/Photositeclient/resources/plugins/yandex/angular-ymaps.js:132:26)
    at Scope.$get.Scope.$digest (http://localhost:8080/Photositeclient/resources/angular/angular.js:12357:29)
    at Scope.$get.Scope.$apply (http://localhost:8080/Photositeclient/resources/angular/angular.js:12622:24)
    at http://localhost:8080/Photositeclient/resources/angular/angular.js:14129:36
    at completeOutstandingRequest (http://localhost:8080/Photositeclient/resources/angular/angular.js:4330:10)
    at http://localhost:8080/Photositeclient/resources/angular/angular.js:4631:7


Can you tell what the fix for this?

**Comment by just-boris** [comment]
This is works fine for me.
Is this problem reproducing permanently? Do you see the map on the right side?
![image](https://cloud.githubusercontent.com/assets/812240/7922161/fe7473c2-08b2-11e5-9bfc-1342ae34a09f.png)
